### ISSUE TITLE
curl NTLM authentication fails on websafety

### ISSUE THREAD

**Issue by czlitony** [diladele/websafety#1126]
**Proxy Server**
squid 4.6 + websafety 7.0.0.7A5E
Proxy Auth Type: NTLM

**Client**
Software:
curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy

**Problem**
On Mac when I use curl to send a request through squid server with NTLM authentication, it fails. I have collected squid server log as below:
_2019-Apr-11 13:03:14| WSAUTH-73324 [DEBUG] 94514209873488/491 => LDAP bind authenticate response (auth result embedded): MIQAAAASAgECYYQAAAAJCgEABAAEAIcA
2019-Apr-11 13:03:14| WSAUTH-73324 [INFO ] 94514209873488/491 => LDAP bind authenticate response SUCCESS:
2019-Apr-11 13:03:14| WSAUTH-73324 [ERROR] helper => panic: empty creds upon successful NTLM authentication
2019/04/11 13:03:14.280 kid1| ERROR: NTLM Authentication validating user. Result: {result=BH, notes={message: critical error: panic: empty creds upon successful NTLM authentication; }}_

Why there is such error "empty creds upon successful NTLM authentication"? I am sure that the credential is correct.

**Comment by ra-at-diladele-com** [comment]
Try looking at what is being exchanged in wireshark - it decodes the NTLM handshake - it might be curl indeed does not send anything.
