### ISSUE TITLE
Possible Missing Reference: Diladele Script (websafety/scripts.ubuntu18/02_apache.sh)

### ISSUE THREAD

**Issue by iic1tls** [diladele/websafety#1210]
Env: Ubuntu 18.04.3 LTS bionic
New Install: Diladele web filter
Issue: Script 06 step:
sudo -u websafety python3 /opt/websafety/var/console/generate.py

Fails with error condition: OpenSSL not installed

when performing a clean installation.

---

My investigation has indicated a possible missing install command in script 2.  Recommend adding the following step:

pip3 install pyopenssl

***

Please re-test this functionality with a clean install of Ubuntu server.

**Comment by ra-at-diladele-com** [comment]
Done thanks!

Added to Ubuntu 18 and Debian 10 scripts in master.
