### ISSUE TITLE
Auth: Shall we also support Pseudo Auth like Captive Portal?

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety#136]
![captive_portal](https://cloud.githubusercontent.com/assets/2544598/24908358/0f04b8ee-1ec0-11e7-8cce-b947ab3ab8b1.png)

**Comment by ra-at-diladele-com** [comment]
this seems like a big project; postponing after 5.2

**Comment by ra-at-diladele-com** [comment]
https://www.dokuwiki.tachtler.net/doku.php?id=tachtler:squid_centos_7#portal_splash_pages

**Comment by johannrichard** [comment]
Besides a "simple" time based Captive Portal with authentication, I would like to also suggest a Voucher based approach for that. This would, to some extent, allow for more granular control of how much time is used up.

Formally, I see the following high-level requirements for such an approach

- Captive Portal with time-based Vouchers 
- Creation of batches of Vouchers for Export 
- Management of Voucher Codes in Diladele Webinterface
- Possibility to use excluded or trusted or other specific domains (to be defined what's most useful) to be accessible without Auth

The last point is especially necessary for scenarios where a device should regularly "ping" home, for example with mobile device management solutions and profile enforcement on different platforms, e.g. something like Meraki, or services like iMessages which require regular "ping backs" to remain activated. Those kinds of APIs usually reside on specific domains that can easily be identified.

**Comment by ra-at-diladele-com** [comment]
https://docs.diladele.com/administrator_guide_develop/proxy_authentication/captive_portal.html
