### ISSUE TITLE
Web UI Password issue

### ISSUE THREAD

**Issue by eirrucsemaj** [diladele/websafety#1461]
Hi,

I have installed Websafety 7.4, but have managed to mess up the Root password (Passw0rd)for the Web UI. I was too tired, and didn't enter int properly as it was saving to Lastpass, and hence the password no longer works.
Is there a way that this can be recovered? I have a full back up of Websafety, I just need instructions on how to restore manually so that the password is reset.

Many thanks
James

**Comment by ra-at-diladele-com** [comment]
Sure, see https://docs.diladele.com/faq/webui/password.html

**Comment by eirrucsemaj** [comment]
That’s great thanks heaps. I totally missed that FAQ
