### ISSUE TITLE
Raspberry Pi version of 7.5.0 missing

### ISSUE THREAD

**Issue by eirrucsemaj** [diladele/websafety#1549]
Hi there

I have tried installing Websafety 7.5 on a Raspberry Pi running Buster, but when running script 06.websafety.sh it seems that the package is missing. 

sudo bash 06_websafety.sh
--2020-05-27 12:22:21--  http://packages.diladele.com/websafety-core/7.5.0.B6BF/armhf/release/debian10/websafety-7.5.0.B6BF_armhf.deb
Resolving packages.diladele.com (packages.diladele.com)... 78.47.119.33
Connecting to packages.diladele.com (packages.diladele.com)|78.47.119.33|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-05-27 12:22:21 ERROR 404: Not Found.

dpkg: error: cannot access archive 'websafety-7.5.0.B6BF_armhf.deb': No such file or directory

The 7.4 version of websafety is located here which I've used to resintall the previous version for now.

http://packages.diladele.com/websafety-core/7.4.0.894A/armhf/release/debian10/websafety-7.4.0.894A_armhf.deb

Are you able to supply the exact location of the 7.5.0 version for armhf architecture for Raspberry PI?

Thanks

**Comment by ra-at-diladele-com** [comment]
We just do not built id ever so often while doing active development - it takes around 3 hours of worktime to build. Closer to release date I will put it out :(
