### ISSUE TITLE
ARM64 version?

### ISSUE THREAD

**Issue by groninge01** [diladele/websafety#1554]
Hi,

I want to run Websafety on an Odroid C2. The cpu arch is arm64. Unfortunately there is no precompiled deb package for it.
Can you supply an arm64 package or if you can point me to the sources I can compile the arm64 package myself.
Squid and clamav are already installed with the correct arch packages.

**Comment by mrbluecoat** [comment]
..any update? I don't see arm64 packages either

**Comment by mrbluecoat** [comment]
Not found:
https://packages.diladele.com/websafety-core/8.1.0.8A10/arm64/release/debian11/websafety-8.1.0.8A10_arm64.deb
https://packages.diladele.com/websafety-core/8.2.0.83CB/arm64/release/debian11/websafety-8.2.0.83CB_arm64.deb
