### ISSUE TITLE
Dockerfile does not include ClamAV compilation, hence no AV check is possible

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety#1651]
```
As soon as I activate the iCAP, Squid is can't Run, because ClamAV is not running.
Cache.log:
2021/10/14 08:49:41| Loading Squid module from '/usr/local/lib/ecap_clamav_adapter.so'
2021/10/14 08:49:41| FATAL: file not found
exception location: LoadableModule.cc(47) load
Squid Status:
Command /usr/bin/squidclient -p 3128 -h 127.0.0.1 mgr:info failed.
```

**Comment by ra-at-diladele-com** [comment]
The steps described above only install eCAP loadable module for clamd - and although Squid indeed starts, the ClamD itself is not operational (not running). So we need to do some more research on how to make the clamd daemon run as our other daemons.

**Comment by ra-at-diladele-com** [comment]
Stopped on release-8.0-clamav - in diladele/docker-websafety repo - need to research further.

**Comment by giorgobiani** [comment]
I'm also having this issue and will highly appreciate if it's fixed or workaround suggested.

**Comment by ra-at-diladele-com** [comment]
There is no more Docker support in Web Safety 9.0, closing.
