### ISSUE TITLE
Admin UI: use the same certs for HTTPS for Admin UI

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety#167]
According to https://docs.diladele.com/faq/webui/https.html we need to generate certs to switch Apache to serve our Admin UI through HTTPS.

May it possible to use Root CA from /opt/websafety/etc for the same purpose?

**Comment by flames** [comment]
Hello Rafael, thanks for creating this issue.

My previous thought was, that websafety already creates a rootCA and uses it for squid certificates. So it would be possible to jump over the step to create own rootCA.
After deeper digging into squid techniques, i found squid uses ssl_crtd to genereate its mimic certs w/o openssl or rootCA
Now, the solution is simple, create own rootCA, generate new rootCA certs and upload them into websafety webui, then create server certificates and sign them with the own rootCA, and use this certs in apache.

maybe it could be automated in websafety for some future release. so far here a little step by step tutorial:



# Prepare root CA and create root certificates
mkdir -p certs/ca
openssl genrsa -out certs/ca/myca.key.pem 2048
openssl req -x509 -new -nodes -key certs/ca/myca.key.pem -days 3650 -out certs/ca/myca.crt.pem -subj "/C=CH/ST=SG/L=Sankt Gallen/O=Your company name/CN=example.tld"



## Create root certificate bundle for websafety
cat certs/ca/myca.crt.pem certs/ca/myca.key.pem > certs/ca/myca.pem
openssl x509 -in certs/ca/myca.pem -outform DER -out certs/ca/myca.der
cp certs/ca/myca.{pem,der} /opt/websafety/etc/

# Regenerate squid certificate storage
rm -R -f /var/spool/squid_ssldb
/usr/lib/squid/ssl_crtd -c -s /var/spool/squid_ssldb
chown -R proxy:proxy /var/spool/squid_ssldb



Create key and CSR for server certificates
mkdir -p certs/{servers,csr}
mkdir -p "certs/servers/proxy.example.tld"
openssl genrsa -out "certs/servers/proxy.example.tld/privkey.pem" 2048
openssl req -new -key "certs/servers/proxy.example.tld/privkey.pem" -out "certs/csr/proxy.example.tld.csr.pem" -subj "/C=CH/ST=Your state/L=Your city/O=Your company name/CN=proxy.example.tld"

# Sign CSR
openssl x509 -req -in certs/csr/proxy.example.tld.csr.pem -CA certs/ca/myca.crt.pem -CAkey certs/ca/myca.key.pem -CAcreateserial -out certs/servers/proxy.example.tld/cert.pem -days 1825

# Create server certificate bundles
cp certs/ca/myca.crt.pem certs/servers/proxy.example.tld/chain.pem
cat certs/servers/proxy.example.tld/privkey.pem certs/servers/proxy.example.tld/cert.pem > certs/servers/proxy.example.tld/server.pem
cat certs/servers/proxy.example.tld/privkey.pem certs/servers/proxy.example.tld/cert.pem certs/ca/myca.crt.pem > certs/servers/proxy.example.tld/fullchain.pem



# Configure apache vhost
mkdir /etc/apache2/ssl
cp certs/servers/proxy.example.tld/* /etc/apache2/ssl/

# Edit (create) /etc/apache2/sites-available/websafety_ssl.conf
<VirtualHost *:443>
    ServerName  proxy.example.tld
    ServerAdmin administrator@example.tld

    WSGIDaemonProcess diladele.lan python-path=/opt/websafety/var/console user=websafety group=websafety display-name=%{GROUP}
    WSGIProcessGroup  diladele.lan
    WSGIScriptAlias / /opt/websafety/var/console/console/wsgi.py

    <Directory /opt/websafety/var/console>
        <Files wsgi.py>
            Order deny,allow
            Allow from all

            # comment the following for debian 7
            Require all granted
        </Files>
    </Directory>

    Alias /static/ /opt/websafety/var/console/www/static/
    <Directory /opt/websafety/var/console/www/static>
        Order deny,allow
        Allow from all

        # comment the following for debian 7
        Require all granted
    </Directory>

    SSLEngine on
    SSLCertificateFile /etc/apache2/ssl/cert.pem
    SSLCertificateKeyFile /etc/apache2/ssl/privkey.pem
    SSLCACertificateFile /etc/apache2/ssl/chain.pem
</VirtualHost>

# Edit (create) /etc/apache2/sites-available/websafety_rewrite.conf
<VirtualHost *:80>
    ServerName  proxy.example.tld
    ServerAdmin administrator@example.tld

    RewriteEngine On
    RewriteCond %{SERVER_PORT} !^443$
    RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
</VirtualHost>

# Reconfigure apache
a2enmod ssl rewrite
a2dissite websafety.conf
a2ensite websafety_rewrite.conf websafety_ssl.conf
systemctl restart apache2.service

**Comment by ra-at-diladele-com** [comment]
Thanks! I will take a look how to make it from Web UI. The sync technology already uses the  root ca from /opt/websafety/etc/myca.pem to validate the sync node - so it should be possible!

**Comment by flames** [comment]
where is the rootCA path? /opt/websafety/etc/myca.pem and /opt/websafety/etc/myca.der are just the certificates, but there is no ca configuration.
i.e. when i try to create key and csr for server certificates using the path /opt/websafety/etc/ it is not working. so i did setup an own ca in /opt/ca and using that. while the resulting ca certificates are fully compatible with websafety, and when installed on client, also the server certificates are trusted.
maybe i missed something in /opt/websafety/etc, will recheck it again and try to create a ca config there to see if it conflicts with websafety in any way (shouldn't conflict actually)
Best, Arthur

**Comment by ra-at-diladele-com** [comment]
Just updated https://docs.diladele.com/faq/webui/https.html (with limitations).

**Comment by flames** [comment]
ah, very cool. even simplier. i missed in signing the certificate

**Comment by ra-at-diladele-com** [comment]
https://docs.diladele.com/administrator_guide_develop/web_ui/https.html
