### ISSUE TITLE
docker: after enabling captive portal, proxy server returns error "Internal Error: Missing Template /opt/websafety/etc/squid/portal.html"

### ISSUE THREAD

**Issue by giorgobiani** [diladele/websafety#1922]
I tried to enable Captive Portal. While the functionality is enabled successfully, I'm unable to use it; rather than showing up authentication page, the error is shown:

`Internal Error: Missing Template /opt/websafety/etc/squid/portal.html`

System Version: 8.1-amd64-linux-ubuntu20
Running Method: Via Docker on Debian

**Comment by ra-at-diladele-com** [comment]
In 8.3 it is fixed - but also see #1922
