### ISSUE TITLE
Squid error

### ISSUE THREAD

**Issue by SerhiiZahuba** [diladele/websafety#2234]
After I turn on the antivirus and restart the services, my squid service does not work. My host has 18 GB of RAM. 

Please help

![image](https://github.com/user-attachments/assets/48cb97c8-f09d-41fc-9f7c-37fa480bc7dc)

**Comment by ra-at-diladele-com** [comment]
Good day, I have just re-tried enabling the eCAP av on our test servers and do not see any error directly. Please could you:
- apt update && apt upgrade && reboot the server
- see if there are any erros in in UI/Av/ClamAV and Freshclam logs.

You can cc to support@diladele.com too.

**Comment by ra-at-diladele-com** [comment]
Also the error seem to be from squid, not ecap - please see what is in the /var/log/squid/cache.log - any obvious errors? You can send it to support@diladele.com (at least several hundreds last lines).

**Comment by SerhiiZahuba** [comment]
[log.log](https://github.com/user-attachments/files/16243463/log.log)

my log, 

the problem is only when I turn on the antivirus
- I am using your image for vmware
- I tried to do 
apt update && apt upgrade && reboot the server

**Comment by ra-at-diladele-com** [comment]
The error seems to be related to the opening of the listening sockets on port 3128.

* so may it be you have another process listening on port 3128 in addition to squid?
* may it be you have customized the listening IP address in UI/Squid/Settings/Networks and the machine now has a different IP?




```
/// check FD after clientHttp[s]ConnectionOpened, adjust HttpSockets as needed
static bool
OpenedHttpSocket(const Comm::ConnectionPointer &c, const Ipc::FdNoteId portType)
{
    if (!Comm::IsConnOpen(c)) {
        Must(NHttpSockets > 0); // we tried to open some
        --NHttpSockets; // there will be fewer sockets than planned
        Must(HttpSockets[NHttpSockets] < 0); // no extra fds received

        if (!NHttpSockets) // we could not open any listen sockets at all
            fatalf("Unable to open %s",FdNote(portType));

        return false;
    }
    return true;
}
```

**Comment by SerhiiZahuba** [comment]
In the UI/Squid/Settings/Networks settings, I tried to leave the field empty or write the server IP - it didn't help. At the time of restart service, I checked port 3128 - it is not busy.

![image](https://github.com/user-attachments/assets/6bb92cee-323e-45e0-9074-8855c8eeba54)

**Comment by ra-at-diladele-com** [comment]
Could you send me the UI/Dashboard/Tools/Export/backup (check support checkbox) to support@diladele.com?

**Comment by SerhiiZahuba** [comment]
Sent to you by mail in the subject of letter "2234"

**Comment by SerhiiZahuba** [comment]
Your mail server does not accept archives.
![image](https://github.com/user-attachments/assets/e34c8938-6c2c-4454-aeeb-55f0b51e45b1)


 I have sent an email with a link to a file exchange.

**Comment by ra-at-diladele-com** [comment]
Replied on support@ - lets keep the intermediate conversation there and only add findings here later.

**Comment by ra-at-diladele-com** [comment]
Seems moving a vm to another host (with another CPU) resolved this strange av startup error...
