### ISSUE TITLE
Errors in doc and grafana dashboars

### ISSUE THREAD

**Issue by SerhiiZahuba** [diladele/websafety#2235]
1) https://docs.diladele.com/tutorials/monitoring_proxy_appliance/grafana_dashboards.html

![image](https://github.com/user-attachments/assets/01920884-40b7-4758-a32a-d9729a5f511c)

This links should be 
https://github.com/diladele/websafety/tree/master/appliance/perf/server/dashboards

2) https://github.com/diladele/websafety/blob/master/appliance/perf/server/dashboards/Web%20Safety%20Appliance%20SafeBrowsing.json   error in file 

![image](https://github.com/user-attachments/assets/ad1830c8-7105-4e86-9c11-bc95274d7c3b)

**Comment by ra-at-diladele-com** [comment]
thanks will look into 9.3

**Comment by ra-at-diladele-com** [comment]
The first error fixed with new updates of the docs site; the second one by *not having* a Safe Browsing dashboard exposed at all (consider it work in progress and not released).
