### ISSUE TITLE
wssyncd: connected nodes are shown in UI forever, even if the node is stopped

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety#255]
Web UI just asks the http://127.0.0.1:18889/cluster/nodes upon each refresh of the page.
The list is always populated after a client connects. After client disconnects the list is NOT cleared.

**Comment by ea-at-diladele-com** [comment]
please check the json and show only ones that have a timestamp fresher than 5 minutes.

**Comment by ra-at-diladele-com** [comment]
Closing as it was completely redesigned.
