### ISSUE TITLE
ICAP server issue

### ISSUE THREAD

**Issue by Chrisnetika** [diladele/websafety#554]
is it normal for ICAP server service to stop working after applying community license? Bit annoying see warning message about it stopped.

**Comment by ra-at-diladele-com** [comment]
Yes unfortunately icap web filter is only distributed by the commercial licensing.

Best regards,
Rafael Akchurin

Op 6 jan. 2018 om 23:09 heeft Chrisnetika <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


is it normal for ICAP server service to stop working after applying community license? Bit annoying see warning message about it stopped.
