### ISSUE TITLE
07_clamav.sh fails (Raspbian 9)

### ISSUE THREAD

**Issue by Gill-Bates** [diladele/websafety#665]
Execution of 07_clamav.sh fails after build with this error:
`
Makefile:561: recipe for target 'ecap_clamav_adapter_la-Xaction.lo' failed
make[2]: *** [ecap_clamav_adapter_la-Xaction.lo] Error 1
make[2]: Leaving directory '/home/pi/scripts.debian9/build/ecap_clamav/ecap_clamav_adapter-2.0.0/src'
Makefile:391: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/pi/scripts.debian9/build/ecap_clamav/ecap_clamav_adapter-2.0.0/src'
Makefile:406: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
/home/pi/scripts.debian9/build/ecap_clamav /home/pi/scripts.debian9
/home/pi/scripts.debian9
`

**Comment by WTFMaster** [comment]
Issue affects:
- Original Raspberry Pi
- Minibian Pi

The developer is working on that:

https://answers.launchpad.net/ecap/+question/664973

**Comment by WTFMaster** [comment]
Here is the patch:

wget -q http://www.measurement-factory.com/tmp/ecap/ecap_clamav_adapter-2.0.0.tar.gz
wget -q https://bugs.launchpad.net/ecap/+bug/1752929/+attachment/5068296/+files/min-deduction-v2p0p0.patch
tar -xzf ecap_clamav_adapter-2.0.0.tar.gz
cd ecap_clamav_adapter-2.0.0
patch -p1 < ../min-deduction-v2p0p0.patch
---------

**Comment by ra-at-diladele-com** [comment]
Postponed

**Comment by ra-at-diladele-com** [comment]
Fixed in #1391. Closing.
