### ISSUE TITLE
FR: Adding time/traffic-budgets to Users

### ISSUE THREAD

**Issue by Gill-Bates** [diladele/websafety#702]
I would apprechiate to add time and traffic budgets to users.

Time: x hours in general / x hours per day
Traffic: x MB in general / x Mb per day

After cunsuming the ammount of Budget, Web Safety should redirect to a blocking page.

**Comment by ra-at-diladele-com** [comment]
Implemented the bandwidth throttling as in #51, we do not have plans to implement traffic budgeting the product is not tailored for such use. Closing.
