### ISSUE TITLE
Limit Upload per policy in Websafety

### ISSUE THREAD

**Issue by jonimessi** [diladele/websafety#943]
Hello,
is there a possibility to general limit uploadsize per Websafety policiy for example to 20KB. With this setting we want to achive that a user is possibe to upload any documents, pictures, etc to any webportals.
For normal "surfing" 20KB are enough for uploading.
At the moment we use Dansguardian and there is the possibility to set "maxuploadsize".
Would be very glad for a positiv answer ;)
Best regards,
jonimessi

**Comment by jonimessi** [comment]
Alternatively there is possibility in Squid with Parameter: "request_body_max_size", but if this parameter should only be available for a group of user (for limiting) I don't know if Squid is the right place, or can parameter be set with an ACL maybe?

**Comment by ra-at-diladele-com** [comment]
Yes squid applies to all users; but if you are able to identify them by subnet for example - this should work.

**Comment by jonimessi** [comment]
> 
> 
> Yes squid applies to all users; but if you are able to identify them by subnet for example - this should work.

No should be identified by Active Directory Group

**Comment by ra-at-diladele-com** [comment]
Ok then please wait for the 6.5/6.6 - will try to implement this faster.

**Comment by ra-at-diladele-com** [comment]
Still no intentions to scan the outgoing request, for downloads implemented #51, this one is closed as "will not implement".
