### ISSUE TITLE
CPU % does not always truncate

### ISSUE THREAD

**Issue by QQHeresATissue** [diladele/websafety#995]
In 7.0 VM release, the value passed to the CPU pie chart sometimes spans 15 decimal places.  This causes the % Text to overflow into the memory chart.

![chart_oob](https://user-images.githubusercontent.com/11380639/46928195-fee71500-cffe-11e8-824c-a572e614c7e3.png)

![graph_oob](https://user-images.githubusercontent.com/11380639/46928198-04445f80-cfff-11e8-868a-d281e04f72d4.png)

**Comment by ra-at-diladele-com** [comment]
Switched to psutil, shall be ok now.
